**How to create a Null values in a data**

  - None

  - np.nan`

**fill the value  using Bi variant analysis(recommended)**

In [ ]:
# all NaN values should not fill value one value
# its not a valid method
# whenever fill missing value there always a justification
# why we are doing,on what method we are doing

In [5]:
import numpy as np
import pandas as pd

In [6]:
d={'Education':['Engineering','MBBS','Engineering','MBBS','Engineering'],
   'Salary':[100,120,50,70,np.nan]}
d

{'Education': ['Engineering', 'MBBS', 'Engineering', 'MBBS', 'Engineering'],
 'Salary': [100, 120, 50, 70, nan]}

In [9]:
df3=pd.DataFrame(d)
df3

     Education  Salary
0  Engineering   100.0
1         MBBS   120.0
2  Engineering    50.0
3         MBBS    70.0
4  Engineering     NaN

In [ ]:
# all the salary values take avg and fill it: (100+20+50+70)/4

# Eng and MBBS different fields
# So first divide the data based on field then take avg of those values
#                        (100+50)/2

**we can fill with mean-median-mode**
- if no other options we can go with
  
- but not always
  
- always try for a justification

In [11]:
sal_mean=df3['Salary'].mean()
df3['Salary'].fillna(sal_mean)

0    100.0
1    120.0
2     50.0
3     70.0
4     85.0
Name: Salary, dtype: float64

In [1]:
import pandas as pd
import numpy as np
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
  'Age':[np.nan,22,24,25],
  'City':['Hyd','Blr','Pune',np.nan]}

In [3]:
df2=pd.DataFrame(d)
df2

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

**methods**

- pad

- bfill

- fill

- backfill

In [4]:
df2.fillna(method='pad')

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\2161826927.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

In [5]:
df2

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

In [8]:
df2.ffill()   # previous value replaced with null

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

In [9]:
df2.bfill()   # nan after value replaced with nan

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  24.0  Pune
3  Mahesh  25.0   NaN

In [17]:
df2.fillna(method='ffill')

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\2637084966.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill')

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2  Suresh  24.0  Pune
3  Mahesh  25.0  Pune

In [18]:
df2.fillna(method='backfill')

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\1705690298.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='backfill')

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  24.0  Pune
3  Mahesh  25.0   NaN

In [7]:
# use obj.fill() or obj.bfill() instead
df2.ffill()
df2.bfill()
df2.fillna(method='ffill')
df2.fillna(method='backfill')

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\3070170810.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill')
C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\3070170810.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='backfill')

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  24.0  Pune
3  Mahesh  25.0   NaN

In [6]:
df2.fillna(method='bfill')

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\2667140817.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='bfill')

    Names   Age  City
0  Ramesh  22.0   Hyd
1  Suresh  22.0   Blr
2  Mahesh  24.0  Pune
3  Mahesh  25.0   NaN

In [12]:
df2.fillna(method='ffill',axis=1)   # if we use axis=1 then it will fill the nan value in column to the previous value

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\1255382982.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='ffill',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2     NaN    24.0  Pune
3  Mahesh    25.0  25.0

In [13]:
df2.fillna(method='backfill',axis=1)   # if we use axis=1 then it will fill the nan value in column to the after ** value

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_19992\1941458368.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='backfill',axis=1)

    Names   Age  City
0  Ramesh   Hyd   Hyd
1  Suresh  22.0   Blr
2    24.0  24.0  Pune
3  Mahesh  25.0   NaN

**KKNImputer**

- sklearn

  - impute

     - KNNImputer

       - fit_transform

- it is a distance based method

- neighbour means closet distance once 

- the user will provide i

- instead of taking avg of all the values , first will distance between data points

- which are closet will take those value avg only

In [19]:
data=np.array([[25,50000],[26,52000],[30,60000],[28,np.nan]])
pd.DataFrame(data,columns=['Age','Salary'])

# i want fill the row [28,np.nan]
# look at Age column not income column
# for 28 which values are close: pick only 2 closest points i.e. neighbours
# 26 and 30
# for 26 what is income : 50000
# for 30 what is income : 60000
# take the avg of (52000+60000)/2=56000

    Age   Salary
0  25.0  50000.0
1  26.0  52000.0
2  30.0  60000.0
3  28.0      NaN

In [24]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(data)

array([[2.5e+01, 5.0e+04],
       [2.6e+01, 5.2e+04],
       [3.0e+01, 6.0e+04],
       [2.8e+01, 5.6e+04]])

- For more than one column we need to use **Euclidian Distance**

In [3]:
import numpy as np
import pandas as pd
data1=np.array([[25,170,50000],[26,175,52000],[30,180,60000],[28,178,np.nan]])
pd.DataFrame(data1,columns=['Age','Height','Income'])

    Age  Height   Income
0  25.0   170.0  50000.0
1  26.0   175.0  52000.0
2  30.0   180.0  60000.0
3  28.0   178.0      NaN

In [ ]:
l1=(25,170)    vs   (28,178)
l1=(26,178)    vs   (28,178)
l1=(30,180)    vs   (28,178)

In [26]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(data)

array([[2.50e+01, 1.70e+02, 5.00e+04],
       [2.60e+01, 1.75e+02, 5.20e+04],
       [3.00e+01, 1.80e+02, 6.00e+04],
       [2.80e+01, 1.78e+02, 5.60e+04]])