In [ ]:
**Feature Engineering**Bar charts ,

- So far we have performed feature analysis

    - Data frame quick checks

    - Categorial column analysis

    - Bar charts , pie charts

    - Numerical column analysis

    - Histograms , box plots , outliers

    - Bi-multi variate analysis

   - correlation etc

- Now we need to learn Feature Engineering

     - we will create a new columns for better ML models
 
     - we will perform the **Encoding** , which is convert categorial to Numerical data
 
     - we will do data **transformations**
 
     - we will perform **Scaling : Standardization and Normalization**
 
     - we will perform the **missing value analysis**
 
- simply feature engineering mass our data will be notified

In [ ]:
geminiai-768 number  embedding system
chatgpt- 10
Encoding- 0 or 1
embedding - [0.2,0.3,0.4..............]

In [ ]:
Data read
feature analysis
feature engineering
feature selection - we are selecting important maths
ML
Testing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [2]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

**case_status**

In [3]:
# how many unique labels
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [4]:
# create a mapper
d={'Certified':0,'Denied':1}

In [5]:
visa_df['case_status']
#1 0 1 1 0

0           Denied
1        Certified
2           Denied
3           Denied
4        Certified
           ...
25475    Certified
25476    Certified
25477    Certified
25478    Certified
25479    Certified
Name: case_status, Length: 25480, dtype: object

In [6]:
visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [7]:
# overwrite in same column
visa_df['case_status']=visa_df['case_status'].map(d)

In [8]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [42]:
# visa_df['continent'].unique()

In [43]:
# d={'Asia':0,'Africa':1,'North America':2,'Europe':3,'South America':4,'Oceania':5}

In [44]:
# visa_df['continent']=visa_df['continent'].map(d)

In [45]:
# visa_df

In [9]:
visa_df['continent']

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [10]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [14]:
d={}
for i in range(len(visa_df['continent'].unique())):
    d[i]=i

In [15]:
d

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}

In [18]:
d={}
for i in range(len(visa_df['continent'].unique())):
    d[visa_df['continent'].unique()[i]]=i

In [19]:
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [30]:
labels=sorted(visa_df['continent'].unique())
d={}
for i,j in enumerate(labels):
    print(i)
    print(j)
    d[j]=i
d

0
Africa
1
Asia
2
Europe
3
North America
4
Oceania
5
South America

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [31]:
{i:j for i,j in enumerate(labels)}

{0: 'Africa',
 1: 'Asia',
 2: 'Europe',
 3: 'North America',
 4: 'Oceania',
 5: 'South America'}

In [24]:
labels=sorted(visa_df['continent'].unique())
d={i:j for j,i in enumerate(labels)}
visa_df['continent']=visa_df['continent'].map(d)

In [25]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [ ]:
labels=sorted(visa_df[col].unique())
d={i:j for j,i in enumerate(labels)}
visa_df[col]=visa_df[col].map(d)

In [4]:
# read the data again
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

for col in cat[1:]:
    labels=sorted(visa_df[col].unique())
    d={i:j for j,i in enumerate(labels)}
    visa_df[col]=visa_df[col].map(d)

In [5]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

Gartner == analytics Vidhya
    refer latest trends
plotly bokhe


- last class we performed  the encoding

- we created a dictionary , we map to original data

- overwrite in the same column

- the same we can develop by using sckiti learn library

- installation name : **scikit learn**

- import name : **sklearn**

- Library: **sklearn**

    - modules : **preprocessing**

      - class : **LabelEncoder**

        - method : **fit_transform**

- if any method under a class called method if without class then function

In [1]:
import sklearn
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

In [2]:
sklearn

In [ ]:
# import the class
# save the class
# apply fit transform
# all sklearn package this is common

**fit vs fit_transform**

- if we are finding something then go for **fit**

- if we are finding some new values and using those values

- to modify the data then go for **fit+transform=fit_transform**

- we first developed a dictionary :**fit**

- we used the dictionary and change the data cat to num : **transform**

In [1]:
# import the packages
# read the data
# cat and num

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [5]:
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

In [6]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['continent'])

array([1, 1, 1, ..., 1, 1, 1], shape=(25480,))

In [8]:
visa_df['continent']=le.fit_transform(visa_df['continent'])

In [9]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

######################################################################

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df['continent']=le.fit_transform(visa_df['continent'])

####################################################################

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df[i]=le.fit_transform(visa_df[i])

In [10]:
# read the data again
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])

In [11]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**explore about inverse transform in the lab**

In [2]:
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [3]:
data=le.fit_transform(visa_df['education_of_employee'])

In [4]:
data[:5]

array([2, 3, 0, 0, 3])

In [5]:
le.inverse_transform(data)[:5]

array(['High School', "Master's", "Bachelor's", "Bachelor's", "Master's"],
      dtype=object)

In [6]:
visa_df['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [ ]:
'High School' :2
"Master's" :3
"Bachelor's":0
'Doctorate':1
#####################################################################
# ordinal data
# 'High School'<"Bachelor's" < "Master's" < 'Doctorate'
########################################################################
# 3>2>11.0\
# <"Master's" > 'High School' > 'Doctorate' > "Bachelor's"

# flop ==== avg ==== hit ==== sh === bb === is : ordinal

# ramesh suresh satish mahesh anish akash : nominal

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data=le.fit_transform(visa_df['case_status'])
data

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [12]:
le.inverse_transform(data)

array(['Denied', 'Certified', 'Denied', ..., 'Certified', 'Certified',
       'Certified'], shape=(25480,), dtype=object)

In [15]:
visa_df['case_status']=le.inverse_transform(data)

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data=le.fit_transform(visa_df['continent'])
data

array([1, 1, 1, ..., 1, 1, 1], shape=(25480,))

In [20]:
le.inverse_transform(data)

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [7]:
# again read the data 
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    data=le.fit_transform(visa_df[i])
    visa_df[i]=le.inverse_transform(data)

In [8]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [14]:
dir(LabelEncoder)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sklearn_auto_wrap_output_keys',
 '_validate_params',
 'fit',
 'fit_transform',
 'get_metadata_routing',
 'get_params',
 'inverse_transform',
 'set_output',
 'set_params',
 'transform']

- LabelEncoder use only for **Nominal level data**

- 90% target columns use only **LabelEncoder**

- for ordinal level data will go for **OrdinalEncoder**

- sklearn 
   - preprocessing
      - OrdinalEncoder
          - fit_transform

In [27]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform(visa_df['education_of_employee'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [28]:
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
visa_df['education_of_employee'].unique()
order=['High School', "Master's", "Bachelor's", 'Doctorate']

In [29]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=order)
oe.fit_transform(visa_df['education_of_employee'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [26]:
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
visa_df['education_of_employee'].unique()
order=[['High School', "Master's", "Bachelor's", 'Doctorate']]

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=order)
oe.fit_transform(visa_df[['education_of_employee']])

array([[0.],
       [1.],
       [2.],
       ...,
       [1.],
       [1.],
       [2.]], shape=(25480, 1))

In [28]:
visa_df['education_of_employee']=oe.fit_transform(visa_df[['education_of_employee']])

In [29]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,2.0,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,3.0,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,0.0,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,0.0,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,3.0,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,0.0,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,2.0,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,3.0,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,3.0,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,0.0,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [24]:
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
visa_df['education_of_employee'].unique()
# order=[['High School', "Master's", "Bachelor's", 'Doctorate']]

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform(visa_df[['education_of_employee']])

array([[2.],
       [3.],
       [0.],
       ...,
       [3.],
       [3.],
       [0.]], shape=(25480, 1))

In [26]:
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')
visa_df['continent'].unique()

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform(visa_df[['continent']])

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], shape=(25480, 1))

In [22]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
for i in cat[1:]:
    visa_df[i]=oe.fit_transform(visa_df[[i]])

In [23]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

**One Hot Encoder**

- One hot means at a time only one value **ON**

- Other will be **OFF**

- ON means one value become **True**

- OFF means one value become **False**

- True means one value become **1**

- False means one value become **0**

- for example : **case status** has two unique levels
    - Certified
    
    - Denied

- So one hot encoder creates two new columns

   - case_status_certified

   - case_status_denied

|Case Status | Certified | Denied |
|------------|-----------|--------|
|Certified   |       1   |       0|
|Denied      |0          |1       |
|Certified   |       1   |       0|
|Denied      |0          |1       |

**pd.get_dummies**

In [ ]:
pd.get_dummies(visa_df['case_status'])

In [4]:
pd.get_dummies(visa_df['case_status']).astype(int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [23]:
for i in cat[1:]:
    dummies = pd.get_dummies(visa_df[i]).astype(int)
    visa_df = pd.concat([visa_df, dummies], axis=1)
    visa_df.drop(i,axis=1)

KeyError: 'continent'

In [17]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,...,South,West,Hour,Month,Week,Year,N,Y,Certified,Denied
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,...,0,0,0,0,0,1,0,1,1,0

In [18]:
for col in cat[1:]:
    dummies = pd.get_dummies(visa_df[col], prefix=col).astype(int)
    
    visa_df = pd.concat([visa_df, dummies], axis=1)
    
    visa_df.drop(col, axis=1, inplace=True)   #❗remove original column

print(visa_df.head())

  case_id  no_of_employees  yr_of_estab  prevailing_wage  Africa  Asia  \
0  EZYV01            14513         2007         592.2029       0     1
1  EZYV02             2412         2002       83425.6500       0     1
2  EZYV03            44444         2008      122996.8600       0     1
3  EZYV04               98         1897       83434.0300       0     1
4  EZYV05             1082         2005      149907.3900       1     0

   Europe  North America  Oceania  South America  ...  \
0       0              0        0              0  ...
1       0              0        0              0  ...
2       0              0        0              0  ...
3       0              0        0              0  ...
4       0              0        0              0  ...

   region_of_employment_South  region_of_employment_West  unit_of_wage_Hour  \
0                           0                          1                  1
1                           0                          0                  0
2                           0                          1                  0
3                           0                          1                  0
4                           1                          0                  0

   unit_of_wage_Month  unit_of_wage_Week  unit_of_wage_Year  \
0                   0                  0                  0
1                   0                  0                  1
2                   0                  0                  1
3                   0                  0                  1
4                   0                  0                  1

   full_time_position_N  full_time_position_Y  case_status_Certified  \
0                     0                     1                      0
1                     0                     1                      1
2                     0                     1                      0
3                     0                     1                      0
4                     0                     1                      1

   case_status_Denied
0                   1
1                   0
2                   1
3                   1
4                   0

[5 rows x 112 columns]

In [2]:
for i in cat[1:]:
    visa_df[i] = pd.get_dummies(visa_df[i]).astype(int)

ValueError: Columns must be same length as key

In [5]:
# category encoding :- Converts categories → numbers → binary format
from category_encoders import BinaryEncoder

be = BinaryEncoder()
visa_df = be.fit_transform(visa_df)

!pip install category_encoders 
# we have to instakk this

ModuleNotFoundError: No module named 'category_encoders'

In [7]:
# frequency encoding :- Replace category with frequency (count)
freq = visa_df['continent'].value_counts()
visa_df['continent'] = visa_df['continent'].map(freq)

In [8]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,16861,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,16861,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,16861,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,16861,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,551,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,16861,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,16861,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,16861,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,16861,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,16861,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**count encoding**
- same as frequency

In [12]:
# Step 1: convert target
visa_df['case_status'] = visa_df['case_status'].map({
    'Certified': 1,
    'Denied': 0
})

# Step 2: target encoding
mean = visa_df.groupby('continent')['case_status'].mean()

visa_df['continent'] = visa_df['continent'].map(mean)

In [ ]:
# **hashing encoder: - Uses hash function to convert categories into numbers

from category_encoders import HashingEncoder

he = HashingEncoder(n_components=4)
visa_df= he.fit_transform(visa_df)