**Step-1:Import packages**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Create a Dataframe using list**

In [4]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(Names)

         0
0   Ramesh
1   Suresh
2  Sathish

**step3:- Name the column**

In [ ]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,clumns)
pd.DataFrame(Names,'NAMES')   #W
pd.DataFrame(Names,columns='NAMES')  # w
pd.DataFrame(Names,['NAMES']) # wrong
pd.DataFrame(Names,columns=['NAMES'])   # right

'Names','Age'
['Names','Age']

In [6]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(Names,columns=['NAMES'])

     NAMES
0   Ramesh
1   Suresh
2  Sathish

**Step-4:Change the index**

In [7]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(Names,index=['x','y','z'],columns=['NAMES'])

     NAMES
x   Ramesh
y   Suresh
z  Sathish

In [3]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
pd.DataFrame(Names,
             index=['A','B','C']
             ,columns=['NAMES'])

     NAMES
A   Ramesh
B   Suresh
C  Sathish

In [3]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,columns)
idx=['A','B','C']
cols=['NAMES']
pd.DataFrame(Names,cols,idx)

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [6]:
Names=['Ramesh','Suresh','Sathish']
# pd.DataFrame(data,index,clumns)
idx=['A','B','C']
cols=['NAMES']
pd.DataFrame(Names,idx,cols)

     NAMES
A   Ramesh
B   Suresh
C  Sathish

**Step-5:two columns**

In [16]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
pd.DataFrame(zip(Names,Age))

         0   1
0   Ramesh  20
1   Suresh  22
2  Sathish  24

In [18]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
data=zip(Names,Age)
pd.DataFrame(data,columns=['NAMES','AGE'])

     NAMES  AGE
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [19]:
Names=['Ramesh','Suresh','Sathish']
age=[20,22,24]
data=zip(Names,Age)
cols=['NAMES','AGE']
pd.DataFrame(data,columns=cols)

     NAMES  AGE
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [7]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
data=zip(Names,Age)
cols=['NAMES','AGE']
idx=['A','B','C']
df=pd.DataFrame(data,idx,cols)
len(df)

3

**Step-6:Add the data to empty dataframe**

In [22]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [26]:
# selection or update = []
# functions = ()

Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
data=zip(Names,Age)
cols=['NAMES','AGE']
df=pd.DataFrame(data,columns=cols)
df['NAMES']

0     Ramesh
1     Suresh
2    Sathish
Name: NAMES, dtype: object

In [37]:
df=pd.DataFrame()
df['Names']=['ramesh','Suresh','Sathish']
df['Age']=[20,22,24]

In [38]:
df

     Names  Age
0   ramesh   20
1   Suresh   22
2  Sathish   24

In [10]:
df=pd.DataFrame()
df['Names']=[]

In [7]:
df=pd.DataFrame()
df['Names']=['ramesh','Suresh','Sathish']
df['Age']=[20,22]

ValueError: Length of values (2) does not match length of index (3)

- key error : no column

- value error(dim error) : column length is mismatch(if two given instead of 3)

**Step-7: add the column to existed dataframe**

In [45]:
df['Cites']=['Hyd','Bglr','Delhi']

In [46]:
df

     Names  Age  Cites
0   ramesh   20    Hyd
1   Suresh   22   Bglr
2  Sathish   24  Delhi

**Step-8: Rename the column**

In [4]:
#  i want to rename Cites to city
# df.rename(mapper,index,columns,axis,inplace)
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
City=['hyd','bglr','delhi']
data=[Names,Age,City]
col=['Names','Age','City']
df=pd.DataFrame(data,columns=col)
d={'City':'city'}
df.rename(columns=d)

    Names     Age     city
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [11]:
df.rename(d)

    Names     Age     City
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [12]:
df.rename(d,axis=0)  # assume as axis=0 I need to change index No answer- No error

    Names     Age     City
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [13]:
df.rename(d,axis=1)

    Names     Age     city
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [14]:
df.rename(index=d)

    Names     Age     City
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [54]:
d={'Cites':'city'}    # column
df.rename(d)    # index
df.rename(d,axis=0)    # index
df.rename(d,axis=1) # col ===  work
df.rename(index=d)     # in
df.rename(columns=d)    # column=work

     Names  Age   city
0   ramesh   20    Hyd
1   Suresh   22   Bglr
2  Sathish   24  Delhi

In [15]:
df.rename(d,axis=1) 
df

    Names     Age     City
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [16]:
df.rename(d,axis=1,inplace=True)

In [17]:
df

    Names     Age     city
0  Ramesh  Suresh  Sathish
1      20      22       24
2     hyd    bglr    delhi

In [1]:
l=[20,10,30,40,50]
import random
random.shuffle(l)

In [2]:
l

[50, 20, 40, 10, 30]

In [21]:
df.columns=['Names','Age','City']

In [22]:
df.index=['A','B','C']

In [23]:
df

    Names     Age     City
A  Ramesh  Suresh  Sathish
B      20      22       24
C     hyd    bglr    delhi

In [18]:
df.rename['City':'city']

TypeError: 'method' object is not subscriptable

**Step-9: Drop the column**

In [24]:
df=pd.DataFrame()
df['Names']=['ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['hyd','bglr','delhi']

In [25]:
df

     Names  Age   City
0   ramesh   20    hyd
1   Suresh   22   bglr
2  Sathish   24  delhi

In [39]:
# i want to drop city column
# df.drop(lables,axis,index,columns,level,inplace)
df.drop('City')    # error
df.drop('City',axis=0)    # error
df.drop(index=['City'])  # error
df.drop('City',axis=1)   # work
df.drop(columns=['City'])  # work

KeyError: "['City'] not found in axis"

In [40]:
df.drop('City',axis=1)

     Names  Age
0   ramesh   20
1   Suresh   22
2  Sathish   24

In [3]:
Names=['Ramesh','Suresh','Sathish']
City=['Hyd','Blr','Pune']
Age=[20,22,24]
data=zip(Names,City,Age)
df=pd.DataFrame(data,
               index=['A','B','C'],
               columns=['Names','City','Age'])
###################################################
df.drop('City',axis=1,inplace=True)
df.drop('C',inplace=True)

In [4]:
df

    Names  Age
A  Ramesh   20
B  Suresh   22

- creating a dataframe

- Name the column

- Change the index

- add the columns

- add the data to empty dataframe

- add the column to existing dataframe

- rename the column

- rename all the column and all the index at a time

- drop the column

- drop the index

In [8]:
# create a dataframe
import pandas as pd
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Blr','Pune']
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22   Blr
2  Sathish   24  Pune

In [41]:
df=pd.DataFrame()
df['Names']=['ramesh','Suresh','Sathish']
df['Age']=[20,22,24]

In [42]:
df['Cites']=['Hyd','Bglr','Delhi']

In [43]:
df.drop('Cites',axis=1)

     Names  Age
0   ramesh   20
1   Suresh   22
2  Sathish   24

In [44]:
df.drop(2)

    Names  Age Cites
0  ramesh   20   Hyd
1  Suresh   22  Bglr

In [45]:
df.drop('Cites',axis=1,inplace=True)

In [46]:
df

     Names  Age
0   ramesh   20
1   Suresh   22
2  Sathish   24

In [26]:
df.drop('Cites',axis=1,inplace=True)
df.drop(2)

KeyError: "['Cites'] not found in axis"

In [28]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
City=['hyd','bglr','delhi']
data=[Names,Age,City]
col=['Names','Age','City']
df=pd.DataFrame(data,columns=col)
df.drop('City',axis=1,inplace=True)
df

    Names     Age
0  Ramesh  Suresh
1      20      22
2     hyd    bglr

In [27]:
Names=['Ramesh','Suresh','Sathish']
Age=[20,22,24]
City=['hyd','bglr','delhi']
data=zip(Names,Age,City)
col=['Names','Age','City']
df=pd.DataFrame(data,columns=col)
df.drop('City',axis=1,inplace=True)
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [58]:
df.drop(2,inplace=True)

In [59]:
df

    Names     Age
0  Ramesh  Suresh
1      20      22

In [ ]:
- inplace = True it will drop permanently or it will overwrite

**Step-10: replace**

In [9]:
# create a dataframe
import pandas as pd
Names=['sita','gita','mita']
Age=[21,23,25]
data=zip(Names,Age)
col=['NAMES','AGE']
df=pd.DataFrame(data,columns=col)
df.replace('sita','rita')

  NAMES  AGE
0  rita   21
1  gita   23
2  mita   25

In [10]:
# df.replace(
#     to_replace=None,
#     value=<no_default>,
#     *,
#     inplace: 'bool_t' = False,
#     limit: 'int | None' = None,
#     regex: 'bool_t' = False,
#     method: "Literal['pad', 'ffill', 'bfill'] | lib.NoDefault" = <no_default>,
# ) -> 'Self | None'

# df.replace(to_replace,value)

df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Bglr','Pune']
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Bglr
2  Sathish   24  Pune

In [11]:
df.replace('Hyd','Chennai')   # inplace not happend so it will not overwrite

     Names  Age     City
0   Ramesh   20  Chennai
1   Suresh   22     Bglr
2  Sathish   24     Pune

In [12]:
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Bglr
2  Sathish   24  Pune

In [13]:
df['Names']='Mahesh'
df['Age']=24
df['City']='Hyd'

In [14]:
df

    Names  Age City
0  Mahesh   24  Hyd
1  Mahesh   24  Hyd
2  Mahesh   24  Hyd

In [8]:
df.replace('Ramesh','Mahesh')   # inplace not happened so it will not overwrite

     Names  Age   City
0   Mahesh   20    Hyd
1   Suresh   21   Bglr
2  Sathish   22  Delhi

In [16]:
import pandas as pd
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish','Mahesh']
df['Age']=[20,22,24,24]
df['City']=['Hyd','Bglr','Pune','Hyd']
df

     Names  Age  City
0   Ramesh   20   Hyd
1   Suresh   22  Bglr
2  Sathish   24  Pune
3   Mahesh   24   Hyd

In [17]:
df.replace('Hyd','Chennai')

     Names  Age     City
0   Ramesh   20  Chennai
1   Suresh   22     Bglr
2  Sathish   24     Pune
3   Mahesh   24  Chennai

In [18]:
df['Marks']=[25,24,23,22]

In [19]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22  Bglr     24
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [20]:
df.replace(24,20)

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22  Bglr     20
2  Sathish   20  Pune     23
3   Mahesh   20   Hyd     22

In [21]:
# all the data in same will change
# all the column data will change

df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22  Bglr     24
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

In [ ]:
- in thiss also the age is change so his is disadavantage
- so we have to overcome this like this

In [22]:
df['Marks'].replace(24,20,inplace=True)

C:\Users\PARBATII\AppData\Local\Temp\ipykernel_8164\602866676.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].replace(24,20,inplace=True)

In [23]:
df

     Names  Age  City  Marks
0   Ramesh   20   Hyd     25
1   Suresh   22  Bglr     20
2  Sathish   24  Pune     23
3   Mahesh   24   Hyd     22

**Step-11:np.where**

In [17]:
# i want to change city name to Chennai
# for the canditate who has age 24

In [25]:
import numpy as np

In [ ]:
np.where(condition,True,False)
age==24
True Chennai
False No change

In [27]:
# i need to apply condition on age column
# we need to select a column

con=df['Age']==24
true='Chennai'
false=df['City']

In [28]:
np.where(con,true,false)

array(['Hyd', 'Bglr', 'Chennai', 'Chennai'], dtype=object)

In [29]:
df['City']=np.where(con,true,false)

In [30]:
df

     Names  Age     City  Marks
0   Ramesh   20      Hyd     25
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23
3   Mahesh   24  Chennai     22

In [ ]:
# big4
# Delloite , EY,PWC,KPMG
# MAANG: MICROSOFT,AMAZON,APPLE,NV,GOOGLE
# #                  developer
#                    skills DATA stuctures
# create products
# SQL VS PANDAS   - Mr.Shiv Rama


mr sivrama krishna---- pandas class

**Step-12:Append a row**

In [31]:
df

     Names  Age     City  Marks
0   Ramesh   20      Hyd     25
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23
3   Mahesh   24  Chennai     22

**loc-iloc**

In [ ]:
df.loc[rows,columns]
   rows are index numbers similar to list slice
   l[start:stop:end]
    column are names any column name we can provide
df.iloc[rows,columns]
  rows and columns are index numbers similar to list slice
  l[start:stop:step]

In [32]:
df.loc[[1,2,3]]

     Names  Age     City  Marks
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23
3   Mahesh   24  Chennai     22

In [33]:
df.loc[1:2]

     Names  Age     City  Marks
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23

In [34]:
rows=[1,2,3]
cols=['Age','City']
df.loc[rows,cols]

   Age     City
1   22     Bglr
2   24  Chennai
3   24  Chennai

In [35]:
rows=[1,2,3]
cols=[1,2]   # index['age']=1,index['city']=2
df.iloc[rows,cols]

   Age     City
1   22     Bglr
2   24  Chennai
3   24  Chennai

In [36]:
cols=['Age','City']
df.loc[1:3,cols]

   Age     City
1   22     Bglr
2   24  Chennai
3   24  Chennai

In [38]:
df.loc[len(df)]=['Anish',26,'Mumbai',25]

In [39]:
df

     Names  Age     City  Marks
0   Ramesh   20      Hyd     25
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23
3   Mahesh   24  Chennai     22
4    Anish   26   Mumbai     25

In [37]:
cols=[1,2]
df.iloc[1:3,cols]

   Age     City
1   22     Bglr
2   24  Chennai

In [35]:
df.iloc[1:3,1:2]

   Age
1   21
2   22

In [37]:
df.loc[1]

Names    Suresh
Age          21
City       Bglr
Marks        20
Name: 1, dtype: object

In [38]:
df.loc[2]

Names    Sathish
Age           22
City       Delhi
Marks         23
Name: 2, dtype: object

In [39]:
df.loc[3]

Names     Mahesh
Age           24
City     Chennai
Marks         22
Name: 3, dtype: object

In [40]:
df.loc[4]

KeyError: 4

In [41]:
df.loc[4]=['Anish',25,'Mumbai',26]

In [42]:
df

     Names  Age     City  Marks
0   Ramesh   20      Hyd     25
1   Suresh   21     Bglr     20
2  Sathish   22    Delhi     23
3   Mahesh   24  Chennai     22
4    Anish   25   Mumbai     26

**Step-13:How to save the dataframe**

In [40]:
# directory : where is the file is available
# name:  what is the name of the file
# extension : what is the type of file(extension of the the name file)

# ##########################################
#     SAME PYTHON (LOCATION)PATH
# name: what is the name of the file
# extension :what is the type of file 


# # dataframe variable= df
# name : student
# extension : .csv and .xlsx for pandas

df.to_csv('student.csv')

In [41]:
pd.read_csv('student.csv')

   Unnamed: 0    Names  Age     City  Marks
0           0   Ramesh   20      Hyd     25
1           1   Suresh   22     Bglr     20
2           2  Sathish   24  Chennai     23
3           3   Mahesh   24  Chennai     22
4           4    Anish   26   Mumbai     25

In [42]:
df.to_excel('student.xlsx')

In [43]:
pd.read_excel('student.xlsx')

   Unnamed: 0    Names  Age     City  Marks
0           0   Ramesh   20      Hyd     25
1           1   Suresh   22     Bglr     20
2           2  Sathish   24  Chennai     23
3           3   Mahesh   24  Chennai     22
4           4    Anish   26   Mumbai     25

**Step-14: ignore index**

In [44]:
df.to_csv('student.csv',index=False)

In [45]:
pd.read_csv('student.csv')

     Names  Age     City  Marks
0   Ramesh   20      Hyd     25
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23
3   Mahesh   24  Chennai     22
4    Anish   26   Mumbai     25

In [48]:
df.to_excel('student.xlsx',index=False)

In [49]:
pd.read_excel('student.xlsx')

     Names  Age     City  Marks
0   Ramesh   20      Hyd     25
1   Suresh   22     Bglr     20
2  Sathish   24  Chennai     23
3   Mahesh   24  Chennai     22
4    Anish   26   Mumbai     25

In [ ]:
# take a new notebook
# in your datafiles'
#   visadataset
#   bankdataset pls load that

In [2]:
df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')

In [3]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [7]:
import pandas as pd
Name=['Aman','Priya','Rahul','Sneha','Kiran','John','Meena','Arjun','Sara','David']
Age=[21,22,20,23,None,21,22,20,23,24]
Gender=['M','F','M','F','M','M','F','M','F','M']
Course=['DS','AI','ML','DS','AI','ML','DS','AI','ML','DS','AI','ML','DS']
Marks=[85,90,78,92,88,None,95,80,76,89]
City=['Hyderbad','Delhi','Mumbai','Chennai','Delhi','Mumbai','Hyderbad','Pune','Chennai','Delhi']
Fees=[50000,55000,52000,50000,55000,52000,50000,55000,52000,50000]
data=zip(Name,Age,Gender,Course,Marks,City,Fees)
cols=['Name','Age','Gender','Course','Marks','City','Fees']
df=pd.DataFrame(data,columns=cols)
df.fillna(' ')

    Name   Age Gender Course Marks      City   Fees
0   Aman  21.0      M     DS  85.0  Hyderbad  50000
1  Priya  22.0      F     AI  90.0     Delhi  55000
2  Rahul  20.0      M     ML  78.0    Mumbai  52000
3  Sneha  23.0      F     DS  92.0   Chennai  50000
4  Kiran            M     AI  88.0     Delhi  55000
5   John  21.0      M     ML          Mumbai  52000
6  Meena  22.0      F     DS  95.0  Hyderbad  50000
7  Arjun  20.0      M     AI  80.0      Pune  55000
8   Sara  23.0      F     ML  76.0   Chennai  52000
9  David  24.0      M     DS  89.0     Delhi  50000

In [6]:
df.fillna(' ')

    Name   Age Gender Course Marks      City   Fees
0   Aman  21.0      M     DS  85.0  Hyderbad  50000
1  Priya  22.0      F     AI  90.0     Delhi  55000
2  Rahul  20.0      M     ML  78.0    Mumbai  52000
3  Sneha  23.0      F     DS  92.0   Chennai  50000
4  Kiran            M     AI  88.0     Delhi  55000
5   John  21.0      M     ML          Mumbai  52000
6  Meena  22.0      F     DS  95.0  Hyderbad  50000
7  Arjun  20.0      M     AI  80.0      Pune  55000
8   Sara  23.0      F     ML  76.0   Chennai  52000
9  David  24.0      M     DS  89.0     Delhi  50000