In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
np.__version__

'2.4.2'

In [3]:
pd.__version__

'2.3.3'

In [7]:
plt.__version__

AttributeError: module 'matplotlib.pyplot' has no attribute '__version__'

In [13]:
import matplotlib
!pip show matplotlib

In [8]:
sns.__version__

'0.13.2'

**Read the data**

- Visadataset

- bank dataset

In [10]:
pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\bank.csv')

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [12]:
pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\bank.csv',sep=';')

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

In [4]:
visa_df=pd.read_csv(r'C:\Users\PARBATII\Documents\Data_files\Visadataset.csv')

- head

- tail

- shape

- size

- columns

- dtypes

- isnull

- info

**head**

In [17]:
# visa_df.head(n: 'int' = 5) -> 'Self
# Return the first `n` rows.
visa_df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [18]:
visa_df.head(n=8)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
5,EZYV06,Asia,Master's,Y,N,2339,2012,South,78252.1400,Year,Y,Certified
6,EZYV07,Asia,Bachelor's,N,N,4985,1994,South,53635.3900,Year,Y,Certified
7,EZYV08,North America,Bachelor's,Y,N,3035,1924,West,418.2298,Hour,Y,Denied

**tail**

In [19]:
# visa_df.tail(n: 'int' = 5) -> 'Self'
# Return the last `n` rows.

visa_df.tail()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [20]:
visa_df.tail(7)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25473,EZYV25474,Asia,Bachelor's,Y,N,2421,2007,Northeast,22845.56,Year,Y,Certified
25474,EZYV25475,Africa,Doctorate,N,N,2594,1979,Northeast,51104.78,Year,Y,Certified
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.57,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.79,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

**shape**

In [22]:
visa_df.shape

(25480, 12)

In [5]:
print(f'the number of rows are : {visa_df.shape[0]}')
print(f'the number of columns are :{visa_df.shape[1]}')

the number of rows are : 25480
the number of columns are :12

**columns**

In [23]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [28]:
type(visa_df)

pandas.core.frame.DataFrame

In [29]:
type(visa_df.columns)

pandas.core.indexes.base.Index

In [ ]:
cols=visa_df.columns
cols.index('continent')  # it will give error because it is not list it is pandas.core.indexes.base.Index
                         # so we can not find index directly

In [34]:
cols=visa_df.columns
cols.tolist().index('continent')

1

In [35]:
cols=visa_df.columns
idx=cols.tolist()
idx.index('continent')

1

**dtypes**

In [3]:
visa_df.dtypes()

TypeError: 'Series' object is not callable

In [ ]:
- () it is not necessary not collable error occurs
- () is not present bound method come

In [37]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [ ]:
- series does not have column name

In [7]:
data_types=visa_df.dtypes
type(data_types)

pandas.core.series.Series

In [39]:
type(visa_df)

pandas.core.frame.DataFrame

- series is a key value pair

- series kind of a dictionary

In [8]:
data_types=visa_df.dtypes
data_types.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [9]:
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [10]:
data_types.index

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [ ]:
data_type.keys()
data_type.values
#################################3
data_type.index
data_type.values

- whenever we have series

- we need to separate lists

- so that we can able to create dataframe

In [12]:
visa_df     # df
visa_df.dtypes   # types series
keys=visa_df.keys()    # keys
values=visa_df.values     # values
df1=pd.DataFrame(zip(keys,values),
                 columns=['continent','Data type'])
df1

                continent                                          Data type
0                 case_id  [EZYV01, Asia, High School, N, N, 14513, 2007,...
1               continent  [EZYV02, Asia, Master's, Y, N, 2412, 2002, Nor...
2   education_of_employee  [EZYV03, Asia, Bachelor's, N, Y, 44444, 2008, ...
3      has_job_experience  [EZYV04, Asia, Bachelor's, N, N, 98, 1897, Wes...
4   requires_job_training  [EZYV05, Africa, Master's, Y, N, 1082, 2005, S...
5         no_of_employees  [EZYV06, Asia, Master's, Y, N, 2339, 2012, Sou...
6             yr_of_estab  [EZYV07, Asia, Bachelor's, N, N, 4985, 1994, S...
7    region_of_employment  [EZYV08, North America, Bachelor's, Y, N, 3035...
8         prevailing_wage  [EZYV09, Asia, Bachelor's, N, N, 4810, 2012, M...
9            unit_of_wage  [EZYV10, Europe, Doctorate, Y, N, 2251, 1995, ...
10     full_time_position  [EZYV11, Asia, Master's, N, N, 2465, 2004, Mid...
11            case_status  [EZYV12, Asia, High School, Y, N, 4069, 2005, ...

In [38]:
visa_df
data_types=visa_df.dtypes
keys=data_types.keys()
values=data_types.values
data=zip(keys,values)
df1=pd.DataFrame(data,columns=['continents','Data type'])
df1

               continents Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

**task**

- separate categorial and numerical columns in different list

- using dtype

In [44]:
# idea
# extract keys and values
# apply the for loop
# check the condition if the data type = object then
# append in cat list
# otherwise append in num list

keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat=[]
num=[]
for i,j in zip(keys,values):
    if j=='object':
        cat.append(i)
    else:
        num.append(i)
cat,num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

In [40]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat=[]
num=[]
for i,j in zip(keys,values):
    if j=='object':
        cat.append(j)
    else:
        num.append(j)
cat,num

([dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O')],
 [dtype('int64'), dtype('int64'), dtype('float64')])

In [43]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat=[]
num=[]
for i,j in zip(keys,values):
    if j==object:
        cat.append([i,j])
    else:
        num.append([i,j])
cat,num

([['case_id', dtype('O')],
  ['continent', dtype('O')],
  ['education_of_employee', dtype('O')],
  ['has_job_experience', dtype('O')],
  ['requires_job_training', dtype('O')],
  ['region_of_employment', dtype('O')],
  ['unit_of_wage', dtype('O')],
  ['full_time_position', dtype('O')],
  ['case_status', dtype('O')]],
 [['no_of_employees', dtype('int64')],
  ['yr_of_estab', dtype('int64')],
  ['prevailing_wage', dtype('float64')]])

In [5]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
cat=[]
num=[]
for i,j in zip(keys,values):
    if j==object:
        cat.extend([i,j])
    else:
        num.extend([i,j])
cat,num

(['case_id',
  dtype('O'),
  'continent',
  dtype('O'),
  'education_of_employee',
  dtype('O'),
  'has_job_experience',
  dtype('O'),
  'requires_job_training',
  dtype('O'),
  'region_of_employment',
  dtype('O'),
  'unit_of_wage',
  dtype('O'),
  'full_time_position',
  dtype('O'),
  'case_status',
  dtype('O')],
 ['no_of_employees',
  dtype('int64'),
  'yr_of_estab',
  dtype('int64'),
  'prevailing_wage',
  dtype('float64')])

In [61]:
data_types=visa_df.dtypes
cat=[]
num=[]
for i in data_types.keys():
    if data_types[i]=='object':
        cat.append([i,data_types[i]])
    else:
        num.append([i,data_types[i]])    
        
cat,num
print(*cat,sep='\n')
print()
print(*num,sep='\n')

['case_id', dtype('O')]
['continent', dtype('O')]
['education_of_employee', dtype('O')]
['has_job_experience', dtype('O')]
['requires_job_training', dtype('O')]
['region_of_employment', dtype('O')]
['unit_of_wage', dtype('O')]
['full_time_position', dtype('O')]
['case_status', dtype('O')]

['no_of_employees', dtype('int64')]
['yr_of_estab', dtype('int64')]
['prevailing_wage', dtype('float64')]

In [30]:
data_types.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [23]:
data_types=visa_df.dtypes
cat=[]
num=[]
for i in data_types:
    if i=='object':
        cat.append(i)
    else:
        num.append(i)
cat,num

([dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O'),
  dtype('O')],
 [dtype('int64'), dtype('int64'), dtype('float64')])

In [55]:
data_types=visa_df.dtypes
cat=[]
num=[]
for i in data_types.keys():
    if data_types[i]=='object':
        cat.extend([(i,data_types[i])])
    else:
        num.extend([(i,data_types[i])])
# cat,num
print(cat)
print(num)

[('case_id', dtype('O')), ('continent', dtype('O')), ('education_of_employee', dtype('O')), ('has_job_experience', dtype('O')), ('requires_job_training', dtype('O')), ('region_of_employment', dtype('O')), ('unit_of_wage', dtype('O')), ('full_time_position', dtype('O')), ('case_status', dtype('O'))]
[('no_of_employees', dtype('int64')), ('yr_of_estab', dtype('int64')), ('prevailing_wage', dtype('float64'))]

In [48]:
# visa_df

In [50]:
visa_df.iloc[100:105,3:7]  # df
visa_df.iloc[100]  # series
visa_df.iloc[[100]]  # df
visa_df.iloc[[100,200,300],]  # df
visa_df.iloc[[100,200,300],:]  # df
visa_df.iloc[:,[3,6,9]]   # df
visa_df.iloc[:,3]   # series
visa_df.iloc[:,[3]]  # df
visa_df.iloc[:,:]  # df

In [62]:
visa_df.iloc[100:105,3:7]

    has_job_experience requires_job_training  no_of_employees  yr_of_estab
100                  Y                     N             2227         2007
101                  Y                     N              334         2007
102                  Y                     N              224         2008
103                  Y                     N              367         1982
104                  Y                     N              306         2003

In [63]:
visa_df.iloc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [64]:
visa_df.iloc[[100]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified

In [65]:
visa_df.iloc[[100,200,300],]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [66]:
visa_df.iloc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [67]:
visa_df.iloc[:,[3,6,9]]

      has_job_experience  yr_of_estab unit_of_wage
0                      N         2007         Hour
1                      Y         2002         Year
2                      N         2008         Year
3                      N         1897         Year
4                      Y         2005         Year
...                  ...          ...          ...
25475                  Y         2008         Year
25476                  Y         2006         Year
25477                  Y         1910         Year
25478                  Y         1887         Year
25479                  Y         1960         Year

[25480 rows x 3 columns]

In [68]:
visa_df.iloc[:,3]

0        N
1        Y
2        N
3        N
4        Y
        ..
25475    Y
25476    Y
25477    Y
25478    Y
25479    Y
Name: has_job_experience, Length: 25480, dtype: object

In [7]:
visa_df.iloc[:,[3]]

      has_job_experience
0                      N
1                      Y
2                      N
3                      N
4                      Y
...                  ...
25475                  Y
25476                  Y
25477                  Y
25478                  Y
25479                  Y

[25480 rows x 1 columns]

In [8]:
visa_df.iloc[:,:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

**isnull**

In [ ]:
visa_df.isnull

In [46]:
visa_df.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

**info**

In [ ]:
It prints a concise summary of the DataFrame, including:

Index details
Column names
Non-null values
Data types
Memory usage

In [13]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB